deployment:
  replicas: 2 #local dev only 1

provider:
  type: Kubernetes

logging:
  level:
    default: debug

service:
  type: LoadBalancer

config:
  envoyGateway:
    extensionApis:
      enableEnvoyPatchPolicy: true
    logging:
      level:
        default: debug
    