version: "3"

vars:
  APP_DIR: app
  BACKEND_DIR: "{{.APP_DIR}}/backend"
  FRONTEND_DIR: "{{.APP_DIR}}/frontend"
  DOCKER_COMPOSE_DIR: app
  BUILD_VERSION:
    sh: git describe --tags --always --dirty 2>/dev/null || echo "v0.0.0"
  BUILD_DATE:
    sh: date +%Y%m%d%H%M
  BUILD_COMMIT:
    sh: git rev-parse --short HEAD 2>/dev/null || echo "unknown"
  BUILD_BRANCH:
    sh: git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown"


includes:
  backend:
    taskfile: ./resources/taskfiles/backend.yaml
    vars:
      BACKEND_DIR: "{{.BACKEND_DIR}}"
  frontend:
    taskfile: ./resources/taskfiles/frontend.yaml
    vars:
      FRONTEND_DIR: "{{.FRONTEND_DIR}}"
  docker:
    taskfile: ./resources/taskfiles/docker.yaml
    vars:
      DOCKER_COMPOSE_DIR: "{{.DOCKER_COMPOSE_DIR}}"
      BUILD_VERSION: "{{.BUILD_VERSION}}"
      BUILD_DATE: "{{.BUILD_DATE}}"
      BUILD_COMMIT: "{{.BUILD_COMMIT}}"
      BUILD_BRANCH: "{{.BUILD_BRANCH}}"
  k8s:
    taskfile: ./resources/taskfiles/k8s.yaml
  envoy:
    taskfile: ./resources/taskfiles/envoy.yaml

tasks:
  default:
    cmds:
      - task --list