version: "3"

vars:
  APP_DIR: app
  BACKEND_DIR: "{{.APP_DIR}}/backend"
  FRONTEND_DIR: "{{.APP_DIR}}/frontend"
  DOCKER_COMPOSE_DIR: app

tasks:

  default:
    cmds:
      - task --list

  # -------------------------
  # Backend
  # -------------------------
  backend:run:
    desc: Run Go backend (migrate + server) locally
    cmds:
      - task: backend:run:migrate
      - task: backend:run:server

  backend:run:server:
    desc: Run Go backend server locally
    dir: "{{.BACKEND_DIR}}"
    deps:
      - task: wire:gen 
        vars:
          folder: "/cmd/server"
    vars:
      gin_mode: '{{.gin_mode | default ""}}'
    env:
      GIN_MODE: '{{.gin_mode}}'
    cmds:
      - go run ./cmd/server

  backend:run:migrate:
    desc: Run Go backend migration locally
    dir: "{{.BACKEND_DIR}}"
    deps:
      - task: wire:gen 
        vars:
          folder: "/cmd/migrate"
    vars:
      flag: '{{.flag}}'
      version: '{{.version}}'
    cmds:
      - go run ./cmd/migrate migrate gorm {{if ne .flag ""}}{{.flag}} {{end}}{{.version}}

  backend:build:
    desc: Build Go backend binary
    dir: "{{.BACKEND_DIR}}"
    deps:
      - wire:gen
    cmds:
      - go build -o bin/server ./cmd/server

  backend:test:
    desc: Run backend tests
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - go test ./...

  backend:tidy:
    desc: Automated adjustment Go module of backend
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - go mod tidy

  # -------------------------
  # go wire
  # -------------------------
  wire:ensure:
    desc: Install wire if not already installed
    status:
      - which wire
    cmds:
      - go install github.com/google/wire/cmd/wire@latest

  wire:gen:
    desc: Run wire code generation
    dir: "{{.dir}}"
    deps:
      - wire:ensure
    vars:
      folder: '{{.folder | default "/cmd"}}'
      dir: '{{.dir | default .BACKEND_DIR}}'
    cmds:
      - wire .{{.folder}}/...

  # -------------------------
  # Frontend
  # -------------------------
  frontend:install:
    desc: Install frontend dependencies
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - npm install

  frontend:dev:
    desc: Run frontend dev server
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - npm run dev

  frontend:build:
    desc: Build frontend
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - npm run build

  # -------------------------
  # Docker
  # -------------------------
  docker:up:
    desc: Start full stack with docker-compose
    dir: "{{.DOCKER_COMPOSE_DIR}}"
    cmds:
      # - docker compose up --build
      - docker compose up -d

  docker:down:
    desc: Stop docker-compose
    dir: "{{.DOCKER_COMPOSE_DIR}}"
    cmds:
      - docker compose down
  
  docker:ps:
    desc: Show running containers
    dir: "{{.DOCKER_COMPOSE_DIR}}"
    cmds:
      - docker compose ps

  docker:logs:
    desc: Show docker logs
    dir: "{{.DOCKER_COMPOSE_DIR}}"
    cmds:
      - docker compose logs -f

  docker:build:
    desc: Build docker images
    dir: "{{.DOCKER_COMPOSE_DIR}}"
    cmds:
      - docker compose build
      
  docker:build:backend:
    desc: Build backend docker image
    dir: "{{.DOCKER_COMPOSE_DIR}}"
    cmds:
      - docker compose build backend

  docker:build:frontend:
    desc: Build frontend docker image
    dir: "{{.DOCKER_COMPOSE_DIR}}"
    cmds:
      - docker compose build frontend

  # -------------------------
  # Kubernetes
  # -------------------------
  k8s:apply:
    desc: Apply k8s manifests
    vars:
      env: '{{.env | default "local"}}'
    cmds:
      - task: k8s:apply:bootstrap
        vars:
          env: '{{.env}}'
      - kubectl wait --for=condition=Ready certificate/my-cert-keygen -n {{.env}} --timeout=30s
      - task: k8s:apply:app
        vars:
          env: '{{.env}}'
      
  k8s:apply:app:
    desc: Apply k8s manifests for app only
    vars:
      env: '{{.env | default "local"}}'
    cmds:
      - kubectl apply -k deploy/app/overlays/{{.env}}

  k8s:apply:bootstrap:
    desc: Apply k8s manifests for bootstrap only
    vars:
      env: '{{.env | default "local"}}'
    cmds:
      - kubectl apply -k deploy/bootstrap/overlays/{{.env}}

  k8s:delete:
    desc: Delete k8s manifests
    vars:
      env: '{{.env | default "local"}}'
    cmds:
      - kubectl delete ns/{{.env}}
      
  k8s:delete:app:
    desc: Delete k8s manifests for app only
    vars:
      env: '{{.env | default "local"}}'
    cmds:
      - kubectl delete -k deploy/app/overlays/{{.env}}

  k8s:delete:bootstrap:
    desc: Delete k8s manifests for bootstrap only
    vars:
      env: '{{.env | default "local"}}'
    cmds:
      - kubectl delete -k deploy/bootstrap/overlays/{{.env}}

  k8s:get:
    desc: Get all resources
    cmds:
      - kubectl get all -A

  k8s:logs:
    desc: Get backend logs
    cmds:
      - kubectl logs -f deploy/backend

  k8s:restart:
    desc: Restart backend and frontend pods
    cmds:
      - task: k8s:restart:backend
      - task: k8s:restart:frontend

  k8s:restart:backend:
    desc: Restart backend pods
    vars:
      env: '{{.env | default "local"}}'
    cmds:
      - kubectl rollout restart deployment backend -n {{.env}}

  k8s:restart:frontend:
    desc: Restart frontend pods
    vars:
      env: '{{.env | default "local"}}'
    cmds:
      - kubectl rollout restart deployment frontend -n {{.env}}

  # -------------------------
  # Envoy Gateway
  # -------------------------
  envoy:crds:install:
    desc: Install Envoy Gateway CRDs via Helm
    dir: envoy
    cmds:
      - helm template eg-crds oci://docker.io/envoyproxy/gateway-crds-helm -f crds-values.yaml | kubectl apply --server-side -f -
  envoy:crds:uninstall:
    desc: Uninstall Envoy Gateway CRDs
    dir: envoy
    cmds:
      - helm template eg-crds oci://docker.io/envoyproxy/gateway-crds-helm -f crds-values.yaml | kubectl delete -f -
    
  envoy:install:
    desc: Install Envoy Gateway via Helm
    dir: envoy
    cmds:
      # - helm install eg oci://docker.io/envoyproxy/gateway-helm --version v1.8.3 -n envoy-gateway-system --create-namespace --skip-crds -f values.yaml 
      - helm install eg oci://docker.io/envoyproxy/gateway-helm -n envoy-gateway-system --create-namespace --skip-crds -f values.yaml

  envoy:upgrade:
    desc: Upgrade Envoy Gateway via Helm
    dir: envoy
    cmds:
      - helm upgrade eg oci://docker.io/envoyproxy/gateway-helm -n envoy-gateway-system --skip-crds -f values.yaml

  envoy:uninstall:
    desc: Uninstall Envoy Gateway
    dir: envoy
    cmds:
      - helm uninstall eg -n envoy-gateway-system

  envoy:status:
    desc: Check Envoy Gateway
    dir: envoy
    cmds:
      - kubectl get pods -n envoy-gateway-system
      - kubectl get svc -n envoy-gateway-system
