namespace: local

generatorOptions:
  disableNameSuffixHash: true
  
resources:
  - ../../base

patches:
  - path: patch-backend-image.yaml
    target:
      kind: Deployment
      name: backend
      
  - path: patch-frontend-image.yaml
    target:
      kind: Deployment
      name: frontend

secretGenerator:
  - name: backend-secret
    literals:
      - DB_MONGODB_USERNAME=my_app 
      - DB_MONGODB_PASSWORD=mypassword
      - DB_MYSQL_PASSWORD=mypassword
      - DB_REDIS_PASSWORD=mypassword
      

configMapGenerator:
  - name: backend-config
    literals:
      - WEBTRANSPORT_USE_SELF_CERT=false
      - DB_REDIS_MODE=sentinel
      - DB_MONGODB_REPLICA_SET=mongodb
      - DB_MONGODB_HOSTS=mongodb-svc:27017
      - DB_REDIS_ENDPOINTS=redis-sentinel-sentinel:26379 

