apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  template:
    spec:
      containers:
        - name: api
          image: demo-backend-server:latest
          imagePullPolicy: Always
          # imagePullPolicy: IfNotPresent