apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  template:
    spec:
      containers:
        - name: web
          image: demo-frontend:latest
          imagePullPolicy: Always
          # imagePullPolicy: IfNotPresent