apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute
metadata:
  name: webtransport-route
spec:
  parentRefs:
    - name: eg
      sectionName: webtransport
  rules:
    - backendRefs:
        - name: backend
          port: 8443