FROM golang:1.25 AS builder

WORKDIR /app

ARG VER_MODULE="api/internal/frameworks/config"
ARG APP_NAME="go-training-migrate"
ARG ENV_NAME="production"
ARG BUILD_VERSION="v0.0.0"
ARG BUILD_DATE="unknown"
ARG BUILD_COMMIT="unknown"
ARG BUILD_BRANCH="unknown"

COPY go.mod .
COPY go.sum .

RUN go mod download
RUN go install github.com/google/wire/cmd/wire@latest

COPY . .

RUN wire ./cmd/migrate
RUN CGO_ENABLED=0 GOOS=linux go build \
    -ldflags \
    "-X ${VER_MODULE}.appName=${APP_NAME} \
    -X ${VER_MODULE}.envName=${ENV_NAME} \
    -X ${VER_MODULE}.buildVersion=${BUILD_VERSION} \
    -X ${VER_MODULE}.buildTime=${BUILD_DATE} \
    -X ${VER_MODULE}.buildCommit=${BUILD_COMMIT} \
    -X ${VER_MODULE}.buildBranch=${BUILD_BRANCH}" \
    -o migrate \
    ./cmd/migrate

FROM gcr.io/distroless/static

ENV GIN_MODE="release"

WORKDIR /

COPY --from=builder /app/migrate .
COPY --from=builder /app/configs ./configs

ENTRYPOINT ["/migrate"]